#!/bin/bash
git add . #komanda "uzmanāmo" mapju pievienošanai
git config --global user.name Paulaspalvina
git config --global user.email paula.spalvina@edu.rtu.lv
git commit -m "Class_$1"
git push origin main
